# Generated by Django 4.2.2 on 2023-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_author_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4, null=True),
        ),
    ]
